// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R4Clothes.Shared.Models;

namespace R4ClothesAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("R4Clothes.Shared.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HoadonMahoadon")
                        .HasColumnType("int");

                    b.Property<int>("Mahoadon")
                        .HasColumnType("int");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int");

                    b.Property<int?>("SanphamMasanpham")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Tensanpham")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Thanhtien")
                        .HasColumnType("float");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("HoadonMahoadon");

                    b.HasIndex("SanphamMasanpham");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDanhGiaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chitiet")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thoigian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDanhGiaSanPham");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Masanpham");

                    b.ToTable("DanhGiaSanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.HoaDon", b =>
                {
                    b.Property<int>("Mahoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KhachhangMakhachhang")
                        .HasColumnType("int");

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime2");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float");

                    b.Property<int>("Trangthaidonhang")
                        .HasColumnType("int");

                    b.HasKey("Mahoadon");

                    b.HasIndex("KhachhangMakhachhang");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.KhachHang", b =>
                {
                    b.Property<int>("Makhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Hinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Makhachhang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Maloai");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.QuanTri", b =>
                {
                    b.Property<int>("Maquantri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Taikhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Maquantri");

                    b.ToTable("QuanTris");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.SanPham", b =>
                {
                    b.Property<int>("Masanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("Hinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Maloai")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Tensanpham")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Masanpham");

                    b.HasIndex("Maloai");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.HoaDon", "Hoadon")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("HoadonMahoadon");

                    b.HasOne("R4Clothes.Shared.Models.SanPham", "Sanpham")
                        .WithMany()
                        .HasForeignKey("SanphamMasanpham");

                    b.Navigation("Hoadon");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Makhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.SanPham", "SanPham")
                        .WithMany("DanhGiaSanPham")
                        .HasForeignKey("Masanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.HoaDon", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.KhachHang", "Khachhang")
                        .WithMany()
                        .HasForeignKey("KhachhangMakhachhang");

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.SanPham", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("Maloai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.HoaDon", b =>
                {
                    b.Navigation("Chitiethoadons");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.SanPham", b =>
                {
                    b.Navigation("DanhGiaSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
